<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ged</string>
	</array>
	<key>name</key>
	<string>GEDCOM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#record</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>header</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.gedcom</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.gedcom</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=0)\s+(@[A-Z]+\d+@\s+)?([A-Z]+)</string>
		</dict>
		<key>line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.gedcom</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.gedcom</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.other.gedcom</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.other.gedcom</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\d+)\s+([A-Z_]+)(\s+((@[A-Z]+\d+@)|(.+)))?</string>
		</dict>
		<key>record</key>
		<dict>
			<key>begin</key>
			<string>^(0)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.gedcom</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^0)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#header</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gedcom</string>
	<key>uuid</key>
	<string>9e3d3b24-4fcd-4a6a-8ddc-afa0df0f8131</string>
</dict>
</plist>
